module.exports =
  color          : "#FFF"
  background     : "#D35400"
  display        : "inline-block"
  width          : "80px"
  borderRadius   : "3px"
  border         : "solid 1px #D35400"
  padding        : "0px 6px 0px 6px"
  textDecoration : "none"
  textAlign      : "center"
  transition     : "all 0.2s ease"
  textShadow     : "none"
  fontSize       : "12px"
  margin         : "0 10px 0 0"
  cursor         : "pointer"

